### PR TITLE
Uplink c 1.2.2

### PR DESCRIPTION
**Pull request by Erikvv**
Updates uplink-c, renames c bindings and implements added functions.

No BC break in the PHP API.

The added EncryptionKey for multi-tenant buckets is not securing the objects as I would expect. I asked for help in slack. 
=> update: this is fixed, waiting on tag of https://github.com/storj/uplink-c/commit/f6073cab8a5a9c548a5e8589593df08fbb3636c8
=> update: uplink-c 1.2.2 was tagged and updated here in uplink-php

### CODE REVIEW

**Review by stefanbenten — APPROVED** [review]
LGTM

**Comment by D4rk4** [comment]
When we can start using it? Any documentation? We need this bindings. @stefanbenten

**Comment by stefanbenten** [comment]
> When we can start using it? Any documentation? We need this bindings. @stefanbenten 

I relayed this awesome work a couple of times internally.
It's no longer in my reach to decide.
Will bring it up once more.

**Comment by D4rk4** [comment]
> > When we can start using it? Any documentation? We need this bindings. @stefanbenten
> 
> I relayed this awesome work a couple of times internally.
> It's no longer in my reach to decide.
> Will bring it up once more.

Okay, who got the power to merge this with the master branch? =)

**Comment by Erikvv** [comment]
All changes in this PR are moved to #8

**Pull request closed without merging**
