### PR TITLE
Jenkins

### PR DESCRIPTION
**Pull request by Erikvv**
Can you please add the project to Jenkins so I can continue with this?

https://build.dev.storj.io/blue/pipelines

I intend to run the Storj test network in a "sidecar" docker container while running the tests in a PHP container.

### CODE REVIEW

**Comment by stefanbenten** [comment]
Hey @Erikvv ,

just letting you know that i hooked up our Jenkins to build this repository just now.
https://build.dev.storj.io/view/thirdparty/
Feel free to add further tests now!

Let me know, if anything is missing!

**Comment by Erikvv** [comment]
@stefanbenten maybe you need to set up a webhook?

**Comment by mniewrzal** [comment]
It looks that something is wrong with Jenkins file structure https://build.dev.storj.io/blue/organizations/jenkins/uplink-php/detail/PR-5/3/pipeline

**Comment by Erikvv** [comment]
> It looks that something is wrong with Jenkins file structure https://build.dev.storj.io/blue/organizations/jenkins/uplink-php/detail/PR-5/3/pipeline

That's not related. 

The run is not triggered on push. Probably only when it periodically scans the repo.

**Comment by stefanbenten** [comment]
I checked the hook and it was a typo, fixed.

**Comment by Erikvv** [comment]
Thank you

**Comment by Erikvv** [comment]
@stefanbenten it's still not picking it up

**Comment by stefanbenten** [comment]
@Erikvv it delivers the push events, can you push another commit and i'll check?
image

**Comment by Erikvv** [comment]
pushed

**Comment by stefanbenten** [comment]
Okay, found the issue. Sorry for the trouble.

**Comment by Erikvv** [comment]
This seems very close to working, just the last step of getting the access or api key in a format so that I can feed it to the already working php tests.

**Comment by Erikvv** [comment]
I close and reopen this PR because the Jenkins workspace is borked.

**Pull request closed without merging**
