### PR TITLE
Update phpstan

### PR DESCRIPTION
**Pull request by Erikvv**

### CODE REVIEW

**Review by egonelbre — DISMISSED** [review]

**Review by mniewrzal — COMMENTED** [review]
Are changes in code needed after having new checks from new phpstan?

**Comment by Erikvv** [comment]
> Are changes in code needed after having new checks from new phpstan?

Yes and they are already in this PR. You can see in Jenkins that the stage "PHPStan" succeeds.

**Review by mniewrzal — APPROVED** [review]

**Comment by Erikvv** [comment]
rebased

**Review by mniewrzal — APPROVED** [review]

**Comment by Erikvv** [comment]
Merged

**Pull request closed without merging**
